# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d14d5bdf4bdb586a2d37c382994f9698cabdc2179ed80c9f22b46357ab109092cded7928e7ab54dc1436d532ecc48c5834ef6e366ddb60953c079cc21572518

test:
  secret_key_base: ce374549968764ea5c8f943f5c24d916345fa1763e9d07129d28a6ffaa78456e43cc6b3644880c5bdcc3539f5df3f78efcb604215cb02047ef33e03ac5959efc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
